### ISSUE TITLE
data walkthrough organization

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/nf-hackathon-2019#1]
I'm thinking that we should have the following R Markdowns (and potentially ipynb versions of the same walkthroughs):

0_setup.Rmd:
- how to load and use the synapse client
- how to create a .synapseConfig file on their own instance)

1_rnaseq_introduction.Rmd:
- basic walkthrough of RNA-Seq data on synapse

2_drugscreening_introduction.Rmd:
- basic walkthrough of drug screening data on synapse

3_mri_introduction.Rmd:
- basic walkthrough of MRI data - this is not yet possible because we don't have the data

4_exploring_other_data.Rmd:
- other publicly available projects 

How does this sound, @jaybee84 and @sgosline?

**Comment by jaybee84** [comment]
Sounds good.

**Comment by sgosline** [comment]
Sounds good. perhaps we can make individual 'R' and 'Python' directories, so that we can put individual docker files in each? Every dockerfile has to have the same name so can't be in the same directory.

**Comment by allaway** [comment]
Agree that they should be in individual directories for simplicity, but can
we just create one dockerfile with a consistent version of python and R? I
am not sure why we'd need two.

**Comment by sgosline** [comment]
Good point, created #2 to discuss as I'm not sure.
