### ISSUE TITLE
Determine content and number of docker files

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/nf-hackathon-2019#2]
Based on #1 I created a new issue.

`synapser` and `synapsepythonclient` don't really play well together, so it  might be best to have different docker images for Python and R. Furthermore, the `rocker` image I have used automatically boots up Rstudio when you run it, I'm not sure that would work for jupyter but am happy to be proved wrong.

**Comment by allaway** [comment]
I think we technically _could_ have created one single container but it would have required installing rstudio or jupyter from scratch. Of course, we could always just not support rstudio at all - jupyter supports R...

Anyway, assuming most R users prefer Rstudio to jupyter, I created two Dockerfiles, one for rstudio, one for jupyter. We'll have to update as we make more demo documents.
