### ISSUE TITLE
drug screening markdown review request

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/nf-hackathon-2019#3]
Hi @sgosline and @jaybee84 - could you please review a draft of the drug screening data walkthrough? Thanks! 

lives here:
https://www.synapse.org/#!Synapse:syn18691338

**Comment by jaybee84** [comment]
The headers of some of the sections are not rendering in the HTML (just missing a space after the "#")

Suggest adding head(dataset) to give people a sneak peak at what the dataset looks like.

Question regarding section "preparing drug screening data" : would the participants get data that is cleaned up/ filtered ?

**Comment by allaway** [comment]
Thanks for the comments! I made these changes.

No, I am planning on giving them everything. Most of this "preparation" is
narrowing the scope of the data rather than filtering out outliers, but I'd
want participants to assess what to include or exclude based on the
questions they are asking rather than define this a priori for them.
