### ISSUE TITLE
RnaSeq data introduction review request

### ISSUE THREAD

**Issue by jaybee84** [Sage-Bionetworks/nf-hackathon-2019#5]
Please review the html file for the rnaseq data introduction : https://www.synapse.org/#!Synapse:syn18693228

@sgosline @allaway

**Comment by sgosline** [comment]
I put some comments in the PR - see that. What do you both think about making this an R package so that we can load functions easily.

**Comment by jaybee84** [comment]
+1 for making this an R package

**Comment by allaway** [comment]
I commented on the idea of a package in the PR itself
